[08/Jan/2020 04:49:03] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 09:29:12] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 09:33:43] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 09:33:52] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 09:38:06] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 15:00:55] WARNING [django.request:228] Not Found: /robots.txt
[08/Jan/2020 16:50:58] WARNING [django.request:228] Not Found: /wp-admin/install.php
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /wp-includes/wlwmanifest.xml
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /xmlrpc.php
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /blog/wp-includes/wlwmanifest.xml
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /wordpress/wp-includes/wlwmanifest.xml
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /wp/wp-includes/wlwmanifest.xml
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /site/wp-includes/wlwmanifest.xml
[08/Jan/2020 20:18:14] WARNING [django.request:228] Not Found: /cms/wp-includes/wlwmanifest.xml
[08/Jan/2020 23:56:29] WARNING [django.request:228] Not Found: /ads.txt
[09/Jan/2020 03:52:06] WARNING [django.request:228] Not Found: /wp-admin/setup-config.php
[09/Jan/2020 03:52:31] WARNING [django.request:228] Not Found: /wp-admin/install.php
[09/Jan/2020 04:48:06] WARNING [django.request:228] Not Found: /about/#Contact.us
[09/Jan/2020 08:36:05] WARNING [django.request:228] Not Found: /HNAP1/
[09/Jan/2020 14:46:03] WARNING [django.request:228] Not Found: /vpns/
[09/Jan/2020 19:50:59] WARNING [django.request:228] Not Found: /wp-admin/install.php
[09/Jan/2020 23:30:24] WARNING [django.security.csrf:228] Forbidden (Referer checking failed - no Referer.): /
[10/Jan/2020 09:07:32] WARNING [django.request:228] Not Found: /wp-includes/wlwmanifest.xml
[10/Jan/2020 09:07:32] WARNING [django.request:228] Not Found: /xmlrpc.php
[10/Jan/2020 09:07:33] WARNING [django.request:228] Not Found: /blog/wp-includes/wlwmanifest.xml
[10/Jan/2020 09:07:33] WARNING [django.request:228] Not Found: /wordpress/wp-includes/wlwmanifest.xml
[10/Jan/2020 09:07:33] WARNING [django.request:228] Not Found: /wp/wp-includes/wlwmanifest.xml
[10/Jan/2020 09:07:33] WARNING [django.request:228] Not Found: /site/wp-includes/wlwmanifest.xml
[10/Jan/2020 09:07:33] WARNING [django.request:228] Not Found: /cms/wp-includes/wlwmanifest.xml
[10/Jan/2020 20:21:36] WARNING [django.request:228] Not Found: /robots.txt
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /wp-includes/wlwmanifest.xml
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /xmlrpc.php
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /blog/wp-includes/wlwmanifest.xml
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /wordpress/wp-includes/wlwmanifest.xml
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /wp/wp-includes/wlwmanifest.xml
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /site/wp-includes/wlwmanifest.xml
[10/Jan/2020 21:44:54] WARNING [django.request:228] Not Found: /cms/wp-includes/wlwmanifest.xml
[10/Jan/2020 23:56:04] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:07] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:08] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:08] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:08] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:08] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:08] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:09] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:29] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:56:30] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:57:15] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:57:16] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[10/Jan/2020 23:57:17] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/info/views.py", line 11, in get
    stats_minutes = stats_questions * 15
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[11/Jan/2020 01:03:54] WARNING [django.request:228] Not Found: /robots.txt
[11/Jan/2020 01:03:55] WARNING [django.request:228] Not Found: /robots.txt
[11/Jan/2020 03:28:28] WARNING [django.request:228] Not Found: /images/logo_pan_158.gif
[11/Jan/2020 13:23:01] WARNING [django.request:228] Not Found: /wordpress/
[11/Jan/2020 13:23:05] WARNING [django.request:228] Not Found: /wp/
[11/Jan/2020 13:23:07] WARNING [django.request:228] Not Found: /blog/
[11/Jan/2020 13:23:09] WARNING [django.request:228] Not Found: /old/
[11/Jan/2020 13:23:11] WARNING [django.request:228] Not Found: /new/
[11/Jan/2020 13:23:13] WARNING [django.request:228] Not Found: /test/
[11/Jan/2020 13:23:15] WARNING [django.request:228] Not Found: /backup/
[11/Jan/2020 13:23:17] WARNING [django.request:228] Not Found: /temp/
[11/Jan/2020 16:44:58] WARNING [django.request:228] Not Found: /api/v1/pods
[11/Jan/2020 19:43:19] WARNING [django.request:228] Not Found: /global-protect/portal/css/login.css
[11/Jan/2020 19:56:57] WARNING [django.request:228] Not Found: /osjdmfjiwdruehnjqfefhrwui
[11/Jan/2020 23:38:53] WARNING [django.request:228] Not Found: /robots.txt
[12/Jan/2020 03:22:31] WARNING [django.request:228] Not Found: /cgi-bin/config.exp
[12/Jan/2020 07:38:21] WARNING [django.request:228] Not Found: /robots.txt
[12/Jan/2020 12:38:34] WARNING [django.request:228] Not Found: /robots.txt
[12/Jan/2020 14:45:31] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[12/Jan/2020 14:52:54] WARNING [django.request:228] Not Found: /files/6027236791698156/13g.html
[12/Jan/2020 14:53:08] WARNING [django.request:228] Not Found: /files/6027236791698156/13g.html
[12/Jan/2020 15:16:25] WARNING [django.request:228] Not Found: /1_year/next_challenge
[12/Jan/2020 15:17:48] WARNING [django.request:228] Not Found: /1_year/next_challenge
[12/Jan/2020 15:17:51] ERROR [django.request:228] Internal Server Error: /challenge/1_year/next_challenge/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 92, in get
    random_challenge = Challenge.random()
TypeError: random() missing 1 required positional argument: 'self'
[12/Jan/2020 15:21:07] ERROR [django.request:228] Internal Server Error: /challenge/1_year/next_challenge/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 99, in get
    random_challenge = self.get_random_challenge()
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 90, in get_random_challenge
    max_id = Challenge.objects.all().aggregate(max_id=Max("id"))['max_id']
NameError: name 'Max' is not defined
[12/Jan/2020 15:21:08] ERROR [django.request:228] Internal Server Error: /challenge/1_year/next_challenge/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 99, in get
    random_challenge = self.get_random_challenge()
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 90, in get_random_challenge
    max_id = Challenge.objects.all().aggregate(max_id=Max("id"))['max_id']
NameError: name 'Max' is not defined
[12/Jan/2020 15:21:09] ERROR [django.request:228] Internal Server Error: /challenge/1_year/next_challenge/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 99, in get
    random_challenge = self.get_random_challenge()
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 90, in get_random_challenge
    max_id = Challenge.objects.all().aggregate(max_id=Max("id"))['max_id']
NameError: name 'Max' is not defined
[12/Jan/2020 15:57:14] ERROR [django.request:228] Internal Server Error: /challenge/1_year/next_challenge/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 101, in get
    random_challenge = self.get_random_challenge()
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 94, in get_random_challenge
    pk = random.randint(1, max_id)
  File "/root/.virtualenvs/venv/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
[12/Jan/2020 16:07:13] WARNING [django.request:228] Not Found: /files/8/8k.html
[12/Jan/2020 16:07:13] WARNING [django.request:228] Not Found: /files/8/10q.html
[12/Jan/2020 16:07:13] WARNING [django.request:228] Not Found: /files/8/13g.html
[12/Jan/2020 16:07:13] WARNING [django.request:228] Not Found: /files/8/10k.html
[12/Jan/2020 16:07:22] WARNING [django.request:228] Not Found: /files/1/10q.html
[12/Jan/2020 16:07:22] WARNING [django.request:228] Not Found: /files/1/10k.html
[12/Jan/2020 16:07:22] WARNING [django.request:228] Not Found: /files/1/13g.html
[12/Jan/2020 16:07:22] WARNING [django.request:228] Not Found: /files/1/8k.html
[12/Jan/2020 16:07:25] WARNING [django.request:228] Not Found: /files/1/10k.html
[12/Jan/2020 16:07:25] WARNING [django.request:228] Not Found: /files/1/8k.html
[12/Jan/2020 16:07:25] WARNING [django.request:228] Not Found: /files/1/10q.html
[12/Jan/2020 16:07:25] WARNING [django.request:228] Not Found: /files/1/13g.html
[12/Jan/2020 16:07:28] WARNING [django.request:228] Not Found: /files/1/10k.html
[12/Jan/2020 16:07:28] WARNING [django.request:228] Not Found: /files/1/8k.html
[12/Jan/2020 16:07:28] WARNING [django.request:228] Not Found: /files/1/10q.html
[12/Jan/2020 16:07:28] WARNING [django.request:228] Not Found: /files/1/13g.html
[12/Jan/2020 16:07:32] WARNING [django.request:228] Not Found: /files/7/8k.html
[12/Jan/2020 16:07:32] WARNING [django.request:228] Not Found: /files/7/10k.html
[12/Jan/2020 16:07:32] WARNING [django.request:228] Not Found: /files/7/10q.html
[12/Jan/2020 16:07:32] WARNING [django.request:228] Not Found: /files/7/13g.html
[12/Jan/2020 16:09:43] WARNING [django.request:228] Not Found: /files/7/10q.html
[12/Jan/2020 16:09:43] WARNING [django.request:228] Not Found: /files/7/13g.html
[12/Jan/2020 16:09:43] WARNING [django.request:228] Not Found: /files/7/10k.html
[12/Jan/2020 16:09:43] WARNING [django.request:228] Not Found: /files/7/8k.html
[12/Jan/2020 16:09:44] WARNING [django.request:228] Not Found: /files/7/10k.html
[12/Jan/2020 16:09:44] WARNING [django.request:228] Not Found: /files/7/8k.html
[12/Jan/2020 16:09:44] WARNING [django.request:228] Not Found: /files/7/10q.html
[12/Jan/2020 16:09:44] WARNING [django.request:228] Not Found: /files/7/13g.html
[12/Jan/2020 16:09:51] WARNING [django.request:228] Not Found: /files/5/8k.html
[12/Jan/2020 16:09:51] WARNING [django.request:228] Not Found: /files/5/10k.html
[12/Jan/2020 16:09:51] WARNING [django.request:228] Not Found: /files/5/10q.html
[12/Jan/2020 16:09:51] WARNING [django.request:228] Not Found: /files/5/13g.html
[12/Jan/2020 16:14:00] WARNING [django.request:228] Not Found: /files/9/8k.html
[12/Jan/2020 16:14:00] WARNING [django.request:228] Not Found: /files/9/10k.html
[12/Jan/2020 16:14:00] WARNING [django.request:228] Not Found: /files/9/10q.html
[12/Jan/2020 16:14:00] WARNING [django.request:228] Not Found: /files/9/13g.html
[12/Jan/2020 16:14:35] WARNING [django.request:228] Not Found: /files/8/8k.html
[12/Jan/2020 16:14:35] WARNING [django.request:228] Not Found: /files/8/13g.html
[12/Jan/2020 16:14:35] WARNING [django.request:228] Not Found: /files/8/10q.html
[12/Jan/2020 16:14:35] WARNING [django.request:228] Not Found: /files/8/10k.html
[12/Jan/2020 16:17:36] WARNING [django.request:228] Not Found: /files/8/13g.html
[12/Jan/2020 16:17:36] WARNING [django.request:228] Not Found: /files/8/8k.html
[12/Jan/2020 16:17:36] WARNING [django.request:228] Not Found: /files/8/10k.html
[12/Jan/2020 16:18:09] WARNING [django.request:228] Not Found: /files/8/8k.html
[12/Jan/2020 16:18:13] WARNING [django.request:228] Not Found: /files/8/
[12/Jan/2020 16:18:50] WARNING [django.request:228] Not Found: /challenges_folder/8/8k.html
[12/Jan/2020 17:13:09] WARNING [django.request:228] Not Found: /files/1/10k.html
[12/Jan/2020 17:13:09] WARNING [django.request:228] Not Found: /files/1/8k.html
[12/Jan/2020 17:13:09] WARNING [django.request:228] Not Found: /files/1/13g.html
[12/Jan/2020 17:24:17] WARNING [django.request:228] Not Found: /files/1/13g.html
[12/Jan/2020 17:24:17] WARNING [django.request:228] Not Found: /files/1/10k.html
[12/Jan/2020 17:24:17] WARNING [django.request:228] Not Found: /files/1/8k.html
[12/Jan/2020 17:24:37] WARNING [django.request:228] Not Found: /files/1/8k.html
[13/Jan/2020 02:39:31] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[13/Jan/2020 07:05:31] WARNING [django.request:228] Not Found: /robots.txt
[13/Jan/2020 07:17:22] WARNING [django.request:228] Not Found: /robots.txt
[13/Jan/2020 14:11:14] WARNING [django.request:228] Not Found: /robots.txt
[13/Jan/2020 18:37:28] WARNING [django.request:228] Not Found: /robots.txt
[13/Jan/2020 19:20:01] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[13/Jan/2020 22:13:04] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[13/Jan/2020 22:18:44] WARNING [django.request:228] Not Found: /robots.txt
[13/Jan/2020 22:38:46] WARNING [django.request:228] Not Found: /robots.txt
[14/Jan/2020 00:36:13] WARNING [django.request:228] Not Found: /remote/login
[14/Jan/2020 03:16:03] WARNING [django.request:228] Not Found: /wp-login.php
[14/Jan/2020 05:51:56] WARNING [django.request:228] Not Found: /wordpress/
[14/Jan/2020 05:51:57] WARNING [django.request:228] Not Found: /wp/
[14/Jan/2020 05:51:57] WARNING [django.request:228] Not Found: /blog/
[14/Jan/2020 05:51:57] WARNING [django.request:228] Not Found: /new/
[14/Jan/2020 05:51:57] WARNING [django.request:228] Not Found: /old/
[14/Jan/2020 05:51:57] WARNING [django.request:228] Not Found: /test/
[14/Jan/2020 05:51:58] WARNING [django.request:228] Not Found: /main/
[14/Jan/2020 05:51:58] WARNING [django.request:228] Not Found: /site/
[14/Jan/2020 05:51:58] WARNING [django.request:228] Not Found: /backup/
[14/Jan/2020 05:51:58] WARNING [django.request:228] Not Found: /home/
[14/Jan/2020 05:51:58] WARNING [django.request:228] Not Found: /demo/
[14/Jan/2020 05:51:59] WARNING [django.request:228] Not Found: /cms/
[14/Jan/2020 05:51:59] WARNING [django.request:228] Not Found: /web/
[14/Jan/2020 07:02:35] WARNING [django.request:228] Not Found: /robots.txt
[14/Jan/2020 11:31:20] WARNING [django.request:228] Not Found: /robots.txt
[14/Jan/2020 14:41:05] WARNING [django.request:228] Not Found: /about/#Contact.us
[14/Jan/2020 17:49:01] WARNING [django.request:228] Not Found: /robots.txt
[14/Jan/2020 22:09:53] WARNING [django.request:228] Not Found: /robots.txt
[15/Jan/2020 07:39:08] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[15/Jan/2020 07:49:13] WARNING [django.request:228] Not Found: /robots.txt
[15/Jan/2020 13:36:45] WARNING [django.request:228] Not Found: /provisioning/
[15/Jan/2020 21:34:18] WARNING [django.request:228] Not Found: /robots.txt
[15/Jan/2020 21:34:36] WARNING [django.request:228] Not Found: /robots.txt
[16/Jan/2020 02:14:49] WARNING [django.request:228] Not Found: /.env
[16/Jan/2020 07:08:55] WARNING [django.request:228] Not Found: /robots.txt
[16/Jan/2020 09:57:19] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/phpunit.xsd
[16/Jan/2020 15:28:24] WARNING [django.request:228] Not Found: /robots.txt
[16/Jan/2020 17:57:53] WARNING [django.request:228] Not Found: /robots.txt
[16/Jan/2020 20:41:33] WARNING [django.request:228] Not Found: /robots.txt
[17/Jan/2020 01:51:57] WARNING [django.request:228] Not Found: /vpns/
[17/Jan/2020 02:47:10] WARNING [django.request:228] Not Found: /403926033d001b5279df37cbbe5287b7c7c267fa00thisisascan
[17/Jan/2020 03:43:37] WARNING [django.request:228] Not Found: /HNAP1/
[17/Jan/2020 04:37:04] WARNING [django.request:228] Not Found: /rpc/rpcproxy.dll
[17/Jan/2020 06:34:19] WARNING [django.request:228] Not Found: /provisioning/
[17/Jan/2020 07:13:10] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/phpunit.xml
[17/Jan/2020 07:14:17] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/phpunit.xml
[17/Jan/2020 07:58:23] WARNING [django.request:228] Not Found: /robots.txt
[17/Jan/2020 12:07:17] WARNING [django.request:228] Not Found: /RDWeb/Pages/
[17/Jan/2020 17:00:21] WARNING [django.request:228] Not Found: /index.php
[17/Jan/2020 17:04:02] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[17/Jan/2020 17:57:52] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[18/Jan/2020 07:08:18] WARNING [django.request:228] Not Found: /api/v1
[18/Jan/2020 07:49:14] WARNING [django.request:228] Not Found: /robots.txt
[18/Jan/2020 17:06:18] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/phpunit.xsd
[19/Jan/2020 04:13:35] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[19/Jan/2020 04:13:36] WARNING [django.request:228] Not Found: /index.php
[19/Jan/2020 04:50:01] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[19/Jan/2020 07:08:56] WARNING [django.request:228] Not Found: /robots.txt
[19/Jan/2020 17:04:44] WARNING [django.request:228] Not Found: /index.php
[19/Jan/2020 17:05:21] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[19/Jan/2020 18:10:19] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[19/Jan/2020 20:27:48] WARNING [django.request:228] Not Found: /wp-login.php
[19/Jan/2020 21:28:32] WARNING [django.request:228] Not Found: /robots.txt
[20/Jan/2020 01:10:18] WARNING [django.request:228] Not Found: /robots.txt
[20/Jan/2020 11:06:09] WARNING [django.request:228] Not Found: /robots.txt
[20/Jan/2020 12:06:55] WARNING [django.request:228] Not Found: /robots.txt
[20/Jan/2020 13:18:07] ERROR [django.request:228] Internal Server Error: /challenges/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view challenge.views.ListChallengeView didn't return an HttpResponse object. It returned None instead.
[20/Jan/2020 15:01:13] WARNING [django.request:228] Not Found: /Telerik.Web.UI.WebResource.axd
[20/Jan/2020 19:59:26] WARNING [django.request:228] Not Found: /robots.txt
[20/Jan/2020 20:17:17] WARNING [django.request:228] Not Found: /index.php
[20/Jan/2020 20:17:17] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[20/Jan/2020 20:21:12] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[21/Jan/2020 02:22:28] WARNING [django.request:228] Not Found: /robots.txt
[21/Jan/2020 04:23:59] WARNING [django.request:228] Not Found: /version
[21/Jan/2020 08:22:56] WARNING [django.request:228] Not Found: /robots.txt
[21/Jan/2020 09:54:03] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[21/Jan/2020 09:54:07] WARNING [django.request:228] Not Found: /index.php
[21/Jan/2020 10:00:46] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[21/Jan/2020 10:05:31] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[21/Jan/2020 10:20:24] WARNING [django.request:228] Not Found: /vpns/cfg/smb.conf
[21/Jan/2020 18:11:49] WARNING [django.request:228] Not Found: /robots.txt
[21/Jan/2020 18:59:15] WARNING [django.request:228] Not Found: /polycom/
[22/Jan/2020 04:37:56] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 04:56:23] WARNING [django.request:228] Not Found: /x
[22/Jan/2020 07:08:57] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 09:19:32] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 09:27:51] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 16:28:20] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 18:27:56] WARNING [django.request:228] Not Found: /x
[22/Jan/2020 18:29:21] WARNING [django.request:228] Not Found: /index.php
[22/Jan/2020 19:51:49] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 20:55:39] WARNING [django.request:228] Not Found: /robots.txt
[22/Jan/2020 22:08:20] WARNING [django.request:228] Not Found: /robots.txt
[23/Jan/2020 00:54:38] WARNING [django.request:228] Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[23/Jan/2020 09:07:08] WARNING [django.request:228] Not Found: /wp-login.php
[23/Jan/2020 10:32:14] WARNING [django.request:228] Not Found: /robots.txt
[23/Jan/2020 13:00:15] WARNING [django.request:228] Not Found: /api/v1/pods
[23/Jan/2020 13:10:58] WARNING [django.request:228] Not Found: /xmlrpc.php
[23/Jan/2020 16:40:51] WARNING [django.request:228] Not Found: /robots.txt
[23/Jan/2020 17:47:28] WARNING [django.request:228] Not Found: /x
[23/Jan/2020 18:37:18] WARNING [django.request:228] Not Found: /themes/default/images/logo.png
[23/Jan/2020 21:59:24] WARNING [django.request:228] Not Found: /robots.txt
[24/Jan/2020 00:19:31] WARNING [django.request:228] Not Found: /robots.txt
[24/Jan/2020 07:49:18] WARNING [django.request:228] Not Found: /robots.txt
[24/Jan/2020 17:38:42] WARNING [django.request:228] Not Found: /robots.txt
[24/Jan/2020 20:15:07] WARNING [django.request:228] Not Found: /api/1/http/upstreams
[24/Jan/2020 21:45:30] WARNING [django.request:228] Not Found: /+CSCOE+/logon.html
[24/Jan/2020 21:51:45] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 07:08:59] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 12:51:53] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 16:32:56] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 19:19:16] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 20:07:05] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 20:07:12] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 21:08:13] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 21:10:30] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 21:49:51] WARNING [django.request:228] Not Found: /robots.txt
[25/Jan/2020 23:05:16] WARNING [django.request:228] Not Found: /robots.txt
[26/Jan/2020 01:15:13] WARNING [django.request:228] Not Found: /robots.txt
[26/Jan/2020 01:59:21] WARNING [django.request:228] Not Found: /cgi-bin/config.exp
[26/Jan/2020 09:41:10] WARNING [django.request:228] Not Found: /index.php
[26/Jan/2020 09:47:05] WARNING [django.request:228] Not Found: /robots.txt
[26/Jan/2020 10:15:34] WARNING [django.request:228] Not Found: /wp-login.php
[26/Jan/2020 10:15:46] WARNING [django.request:228] Not Found: /wp-login.php
[26/Jan/2020 11:33:08] WARNING [django.request:228] Not Found: /robots.txt
[26/Jan/2020 12:24:33] WARNING [django.request:228] Not Found: /robots.txt
[26/Jan/2020 12:39:29] ERROR [django.request:228] Internal Server Error: /challenge/5197626439671097/
Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'challenge.statement_10q|filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/django/trainer/website/investmenttrainer/challenge/views.py", line 18, in get
    return render(request, self.template_name, {"challenge": challenge, 'sections': sections, "challenge_type": challenge_type})
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loaders/cached.py", line 53, in get_template
    template = super().get_template(template_name, skip)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 960, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 562, in compile_filter
    return FilterExpression(token, self)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 656, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/root/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 568, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'filename'
